<?php

namespace MA\MainBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateMarque($marque)
    {
        return $this
            ->createQueryBuilder('m')
            ->update('MAMainBundle:Marque', 'm')
            ->set('m.marque', '?1')
            ->setParameter(1, $marque)
            ->getQuery()
            ->getResult();
    }
}
