<?php

namespace MA\MainBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

    public function updateImage($imageId, $annonceId)
    {
        return $this
            ->createQueryBuilder('i')
            ->update('MAMainBundle:Image', 'i')
            ->set('i.annonce', '?1')
            ->where('i.id = ?2')
            ->setParameter(1, $annonceId)
            ->setParameter(2, $imageId)
            ->getQuery()
            ->getResult();
    }
}
