<?php

namespace MA\MainBundle\Repository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function updateMarque($id, $name)
    {
        return $this
            ->createQueryBuilder('m')
            ->update('MAMainBundle:Marque', 'm')
            ->set('m.name', '?1')
            ->where('m.id = ?2')
            ->setParameter(1, $name)
            ->setParameter(2, $id)
            ->getQuery()
            ->getResult();
    }
}
