<?php

namespace MA\MainBundle\Repository;

/**
 * PlacesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlacesRepository extends \Doctrine\ORM\EntityRepository
{
}
